### ISSUE TITLE
Questions please!

### ISSUE THREAD

**Issue by jianlianggao** [apetkau/galaxy-hackathon-2014#1]
Hi,
 I'm confused by the lines in catDocker.xml .  
 (1) input2 is commented out previously. why it still appears in `<`inputs`>` `<`/inputs`>`.
 (2) why there are out_file1 and input in the same line in the `<`outputs`>` `<`/outputs`>`.
 (3) output2 in the outputs is not used in this case, is it?

   Look forward to hearing from you soon, Thank you very much.
   Best,
J

**Comment by apetkau** [comment]
Hello,
1. May I ask where you see input2 commented out in **catDocker.xml**?  Do you mean the lines like `#for $q in $queries` and `#end for`?  These are not interpreted as comments but are interpreted by the Cheetah templating engine used by Galaxy to construct command-line arguments for tools in Galaxy.  You can see more about it at https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Ccommand.3E_tag_set.
2. The **input** values in `<outputs>` are instructing Galaxy to use the same file format as one of the input files for the output file.  See https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Coutputs.3E_tag_set.
3. The file **out_file2** in the outputs is used.

I would recommend looking over the Galaxy documentation on tools in https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax which should be more helpful.  There's also a really nice tutorial at https://planemo.readthedocs.io/en/latest/writing.html.  Or, if I did not answer your questions please let me know.

Aaron

**Comment by jianlianggao** [comment]
Hi Aaron,
   Thank you very much for the detailed. Yes, I misunderstood '#' as comments. I will follow your suggestions and try on my local Galaxy environments. 
   Best regards,
Jianliang
