### ISSUE TITLE
Tool execution results in command not found

### ISSUE THREAD

**Issue by riasc** [apetkau/galaxy-hackathon-2014#2]
Hello,
I have been trying to follow this in 18.09, but I failed in doing so. 
Upon execution I get the following error: 
'galaxy/database/jobs_directory/000/17/tool_script.sh: line 9: smalt_wrapper.py: command not found'
Looks to me as if the container can't be accessed? smalt_wrapper.xml, job_conf.xml and sudoers file are all set up. What am I missing? Must the container be started manually beforer? The catDocker example is working, but I guess it is executed locally, because I don't see the docker run command on the logs. 

Thanks

**Comment by riasc** [comment]
It works now. I was just too blind to see. I had a typo in the job_conf.xml
However, another question that came up. How is it possible to share a folder
with the container as it could have been with the -v parameter of docker?

**Comment by apetkau** [comment]
I'm glad you got it working :smile: 

For sharing a folder, you may want to look into the **docker_volumes** parameter in the Galaxy `job_conf.xml` file (https://github.com/galaxyproject/galaxy/blob/release_18.09/config/job_conf.xml.sample_advanced#L378).

I hope this works out for you.

**Comment by riasc** [comment]
Sorry for the late reply (and for not closing the issue). I didn't had the time to check your solution (the last 6 months xD). Anyways your hint was great. I managed to get it to work with the volumes. Thanks.
